RoR Group Capstone Project: Recipe App
oovillagran/recipe_app pull request #26
Opened 2023-08-12 17:41 UTC by dazehinn

### Features
- created login page and registration page with Devise.
- Food list displays a list of food added by the logged-in user (display also quantity of a given food).
- created a form that allows users to add new food.
- displays a list of recipes created by the logged-in user which leads to recipe details.
- user can delete a recipe
- displays a list of all public recipes which leads to recipe details.
- recipe details displays a toggle button that allows  a recipe to be made public or private.
- Generates shopping list view
- displays the list of food that is missing for all recipes of the logged-in user
- count the total food items and total price of the missing food.
- a navigation menu that allows users to open all  created pages
- unit and integration tests
- fix N+1 queries

Before
![before](https://github.com/oovillagran/recipe_app/assets/100543892/80915013-b69c-4509-8a2c-3bc2f7f24376)

After
![after](https://github.com/oovillagran/recipe_app/assets/100543892/f785cdbe-959e-4bac-a562-29a770483a94)

2023-08-12 19:04 UTC, shella12 requested changes
Hi @dazehinn and @oovillagran , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- All tests passed ✅ 
- App UI matches wireframe ✅  
- Working app ✅   
- Fixed N+1 problem ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-12 19:04 UTC, shella12 commented on spec/views/food_index_spec.rb
> +  end
- [ ] Great job on creating test cases for your project using `rspec` however according to the [project requirements](Write integration tests with capybara gem) you should write your integration tests as well. Please use the required integration tests for your application by using `capybara`.

Project Requirements:
----
Technical setup

> - Set up RSpec and Capybara testing libraries.
> - Write integration tests with capybara gem

2023-08-13 03:55 UTC, Lizdev-05 approved these changes
Hi @dazehinn and @oovillagran , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights

:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 
:heavy_check_mark: All tests pass :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-13 03:58 UTC, oovillagran commented
Thanks @Lizdev-05! 👌

2023-08-13 03:58 UTC, merged